apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heavy-configmaps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dharapandya85/argoCD-testing.git
    targetRevision: HEAD
    path: configs
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true